### PR TITLE
Fix for Qt6 compatibility

### LINKED ISSUE #8: Not loading with Anki 23.10.1
I'm guessing it needs a small update?

> 
> Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
> Platform: macOS-14.1-x86_64-i386-64bit
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-11-10 22:56:52
> 
> When loading Ze Add Note Id:
> Traceback (most recent call last):
>   File "aqt.addons", line 245, in loadAddons
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/886709118/__init__.py", line 1, in <module>
>     from .src import init
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/886709118/src/__init__.py", line 1, in <module>
>     from .field_dialog import init_field_dialog
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/886709118/src/field_dialog.py", line 1, in <module>
>     from PyQt5 import QtWidgets
> ModuleNotFoundError: No module named 'PyQt5'

### PR DESCRIPTION
**Pull request by abdnh**
A trivial fix for Qt errors on 23.10.

Closes #8

### CODE REVIEW

**Comment by hgiesel** [comment]
Thanks!

**Comment by Yang2Gui3zi** [comment]
Sorry, I cannot get these changes to work.  After making and saving the changes to 4 lines of Python code in 3 modules, I then restarted Anki v23.10.1.  I then again saw essentially the same error messages as were seen by AnKingMed in [https://github.com/hgiesel/anki_add_note_id/issues/8](url).  Those error messages ended with this line
`ModuleNotFoundError: No module named 'PyQt5'`

I will hazard a guess that this error recurred because I do not know how to properly  change Python code.  Because Python is a scripting language, I had assumed that all I needed to do was change the source code, which would then be interpreted when Anki executed.  Can it be that I needed to go through some further steps, such as compiling  the source modules and linking the compiled output together?

It has been forty years or more since I wrote any original code, and I never before made any changes to _Python_ code.  Would you be so kind as to tell me what I am missing?

**Comment by abdnh** [comment]
@Yang2Gui3zi You can replace `PyQt5` with `PyQt6` in the gui/settings_ui.py file. it's a generated file that's not committed to the repo, so it's not shown in my changes.

**Comment by Yang2Gui3zi** [comment]
Thanks a great deal, @abdnh .  After I changed `PyQt5` to `PyQt6` in the first line of code in gui/settings_ui.py file, the error message disappeared about add-on Ze Add Note Id failing to load.  I was able to add a new note to my deck, and that note did automatically get allocated a new noteid .  So it seems the problem has been resolved.

However, I am a little concerned about these comment lines in the settings_ui.py file
`# WARNING: Any manual changes made to this file will be lost when pyuic5 is`
`# run again.  Do not edit this file unless you know what you are doing.`
because, of course, I have no idea what I was doing.

For good order's sake, here is that single line of code after I had changed it:
`from PyQt6 import QtCore, QtGui, QtWidgets`

And I attach the original error message:
Add-on Startup failed - Screenshot 2023-11-14 135850

**Comment by abdnh** [comment]
> However, I am a little concerned about these comment lines in the settings_ui.py file

You can ignore that comment. It's only relevant for the add-on's author.

**Pull request merged**
